services:
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ElearningDatabase
    ports:
      - "3307:3306"
    volumes:
      - ./databases/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: elearning_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no

  backend:
    build: ./backend
    container_name: elearning_backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PORT=3306
      - DB_PASSWORD=123456
      - DB_NAME=ElearningDatabase
      - REDIS_URL=${REDIS_URL}
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: elearning_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    depends_on:
      - backend

volumes:
  mysql_data: